<a href="https://colab.research.google.com/github/subbu27iitb/General/blob/main/Word_Embedding_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Embedding Layer**

In [2]:
import tensorflow as tf
tf.__version__

'2.9.2'

In [27]:
from tensorflow.keras.preprocessing.text import one_hot
sentences= ["The glass of milk", 
            "the glass of juice",
            "the cup of tea",
            "I am a good boy",
            "I am a good developer",
            "understand the meaning of words",
            "your videos are good"]
#sentences
voc_size=10000 #tuning parameter

######**One Hot Representation**

In [28]:
#onehot_repr = [one_hot(words,voc_size)for words in sentences]
onehot_repr=[]
for word in sentences:
  onehot_repr.append(one_hot(word,voc_size))

print(onehot_repr)


[[7821, 5034, 7671, 6228], [7821, 5034, 7671, 1226], [7821, 8327, 7671, 1013], [9332, 9584, 178, 7540, 6147], [9332, 9584, 178, 7540, 8973], [7516, 7821, 6684, 7671, 3806], [7048, 2554, 5383, 7540]]


#####**Word Embedding Representation**

In [30]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [32]:
sent_length=8 #tuning parameter
embedded_docs= pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7821 5034 7671 6228]
 [   0    0    0    0 7821 5034 7671 1226]
 [   0    0    0    0 7821 8327 7671 1013]
 [   0    0    0 9332 9584  178 7540 6147]
 [   0    0    0 9332 9584  178 7540 8973]
 [   0    0    0 7516 7821 6684 7671 3806]
 [   0    0    0    0 7048 2554 5383 7540]]


In [34]:
dim=15 #tuning parameter
model= Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
#model.compile('adam', 'mse')
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 15)             150000    
                                                                 
Total params: 150,000
Trainable params: 150,000
Non-trainable params: 0
_________________________________________________________________


In [35]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 209ms/step
[[[ 0.01092567  0.02745217 -0.01794342  0.04038901  0.01116287
    0.0007244   0.03826049  0.03459107  0.00544678  0.01625507
    0.02526123 -0.03021991 -0.02294476 -0.00392444 -0.04790613]
  [ 0.01092567  0.02745217 -0.01794342  0.04038901  0.01116287
    0.0007244   0.03826049  0.03459107  0.00544678  0.01625507
    0.02526123 -0.03021991 -0.02294476 -0.00392444 -0.04790613]
  [ 0.01092567  0.02745217 -0.01794342  0.04038901  0.01116287
    0.0007244   0.03826049  0.03459107  0.00544678  0.01625507
    0.02526123 -0.03021991 -0.02294476 -0.00392444 -0.04790613]
  [ 0.01092567  0.02745217 -0.01794342  0.04038901  0.01116287
    0.0007244   0.03826049  0.03459107  0.00544678  0.01625507
    0.02526123 -0.03021991 -0.02294476 -0.00392444 -0.04790613]
  [ 0.00972145 -0.04689103  0.01224042 -0.0037869   0.03472522
   -0.0028682   0.00432348  0.03761036  0.03666807 -0.04758871
    0.00346757  0.01272957  0.04586424 -0.04164143  0.0367015

In [39]:
print(embedded_docs[0])
print("*******************************************")
print(model.predict(embedded_docs)[0])

[   0    0    0    0 7821 5034 7671 6228]
*******************************************
1/1 [==============================] - 0s 27ms/step
[[ 0.01092567  0.02745217 -0.01794342  0.04038901  0.01116287  0.0007244
   0.03826049  0.03459107  0.00544678  0.01625507  0.02526123 -0.03021991
  -0.02294476 -0.00392444 -0.04790613]
 [ 0.01092567  0.02745217 -0.01794342  0.04038901  0.01116287  0.0007244
   0.03826049  0.03459107  0.00544678  0.01625507  0.02526123 -0.03021991
  -0.02294476 -0.00392444 -0.04790613]
 [ 0.01092567  0.02745217 -0.01794342  0.04038901  0.01116287  0.0007244
   0.03826049  0.03459107  0.00544678  0.01625507  0.02526123 -0.03021991
  -0.02294476 -0.00392444 -0.04790613]
 [ 0.01092567  0.02745217 -0.01794342  0.04038901  0.01116287  0.0007244
   0.03826049  0.03459107  0.00544678  0.01625507  0.02526123 -0.03021991
  -0.02294476 -0.00392444 -0.04790613]
 [ 0.00972145 -0.04689103  0.01224042 -0.0037869   0.03472522 -0.0028682
   0.00432348  0.03761036  0.03666807 -0.0475